Reserve txt
3mdeb/xen pull request #6
Opened 2022-09-02 07:46 UTC by Stojek139808

2022-09-02 15:02 UTC, krystian-hebel requested changes

2022-09-02 15:02 UTC, krystian-hebel commented on xen/arch/x86/boot/head.S
> +        .int 0
```suggestion
        .long 0
```

`.int` is not portable, it can have different size depending on target.

2022-09-02 15:02 UTC, krystian-hebel commented on xen/arch/x86/include/asm/setup.h
> +extern int sl_status;
```suggestion
extern uint32_t sl_status;
```

2022-09-02 15:02 UTC, krystian-hebel commented on xen/arch/x86/tboot.c
>      if ( !tboot_in_measured_env() )
```suggestion
    if ( !tboot_in_measured_env() && sl_status == 0 )
```
Plus `extern uint32_t sl_status;` earlier if needed, and don't comment out this conditional.

2022-09-02 15:02 UTC, krystian-hebel commented on xen/arch/x86/boot/head.S
> +        /* Save information that tboot was used. */
No `tboot` in comment please, it isn't used in this case.

2022-09-04 10:17 UTC, miczyg1 commented on xen/arch/x86/boot/head.S
> +        /* Save information that tboot was used. */
```suggestion
        /* Save information that TrenchBoot slaunch was used. */
```

2022-09-04 10:20 UTC, miczyg1 commented on xen/arch/x86/setup.c
> +        tboot_protect_mem_regions();
You can't use tboot any tboot functions as they depends on other tboot structures and calls done throughout Xen startup. This should be rewritten to native implementation.

2022-09-04 10:21 UTC, miczyg1 commented on xen/arch/x86/tboot.c
> +    if ( !tboot_in_measured_env() && sl_status == 0 )
There should be no chanegs in tboot.c file, we do not care about tboot at all and we should not use any API from this file.

2022-09-05 08:45 UTC, Stojek139808 commented on xen/arch/x86/setup.c
> +        tboot_protect_mem_regions();
I rewrote the function, the only thing remaining for now is function to copy TXT CR values, which is still from tboot. Question is if it really can't be reused. For now it depends on `FIX_TBOOT_MAP_ADDRESS` defined in `asm/fixmap.h`. Can't we just add another entry to enumerate for this rewritten function and leave it at that, to separate it from tboot? Because as of now, I don't know if there is another implementation in xen that would copy the CR's.

2022-09-05 09:03 UTC, miczyg1 commented on xen/arch/x86/setup.c
> +        tboot_protect_mem_regions();
We don't want any relation to tboot. TXT configuration registers are at fixed memory mapped I/O addresses of 0xfed20000 to 0xfed40000. Al lwe need is to use Xen internal functions to mark them as reserved in E820

2022-09-05 17:08 UTC, andyhhp commented
Please also extend `docs/hypervisor-guide/x86/how-xen-boots.rst` to note the new entrypoint.  Only needs to be a sentence, but it's important to keep (what few) docs we have up to date

2022-09-05 17:08 UTC, andyhhp commented on xen/arch/x86/boot/head.S
> +
Spurious whitespace change

2022-09-05 17:08 UTC, andyhhp commented on xen/arch/x86/boot/head.S
> +        .long 0
This will probably be better to move into setup.c.  Amongst other things, it will get proper debug metadata.

2022-09-05 17:08 UTC, andyhhp commented on xen/arch/x86/boot/head.S
> +        jmp __start
What is the entry ABI?  (Please leave a comment by sl_stub_entry stating what it is.  See https://github.com/TrenchBoot/secure-kernel-loader/blob/master/head.S#L52-L68 for an example I made before)

As for `sym_offs()`, it's not correct to use like this.  Xen's entry paths are relocateable, and this will only do the right thing if the load base address happens to be 0.

Ideally, we get this info from the entry ABI, at which point you should set up %esi and use `sym_esi()` instead.

2022-09-05 17:08 UTC, andyhhp commented on xen/arch/x86/setup.c
> +int protect_txt_mem_regions(void)
`static`.  Also `void` as you never check the return value.

2022-09-05 17:08 UTC, andyhhp commented on xen/arch/x86/setup.c
> +    if(sl_status)
`if ( sl_status )`  (just style)

Also, this probably wants to be a little later.  In particular, it ought to be after the first attempt to sanitise the E820 table.

2022-09-05 17:08 UTC, andyhhp commented on xen/arch/x86/tboot.c
> +    if ( !tboot_in_measured_env() && sl_status == 0 )
Yeah, we want to abstract things properly and not call into tboot code in a non-tboot case.  Perhaps we need CONFIG_TRENCHBOOT and some abstractions in a DRTM-"vendor"-neutral header file.

2022-09-06 06:02 UTC, Stojek139808 commented on xen/arch/x86/boot/head.S
> +
Fixed

2022-09-06 06:05 UTC, Stojek139808 commented on xen/arch/x86/boot/head.S
> +        jmp __start
I've changed to sym_esi() like you suggested. But keep in mind that rest of the entry point code was supposed to be added in other PR's.

2022-09-06 06:05 UTC, Stojek139808 commented on xen/arch/x86/setup.c
> +int protect_txt_mem_regions(void)
Fixed

2022-09-06 06:06 UTC, Stojek139808 commented on xen/arch/x86/setup.c
> +    if(sl_status)
Fixed style and moved it a bit later.

2022-09-06 07:54 UTC, andyhhp commented on xen/arch/x86/boot/head.S
> +        movl $1, sym_esi(sl_status)
You missed the `sub` from the sequence which is rather critical.  Without it, you're treating line 409 as if it were the image load base.  Also, you don't have a good stack, do you?

2022-09-06 07:54 UTC, andyhhp commented on xen/arch/x86/setup.c
> -
Still spurious.  When submitting patches upstream, you need to submit them as a "cleanly rebased" set of changes, not as "add extra delta in new commits", which avoids cross-patch errors like this.

2022-09-06 07:54 UTC, andyhhp commented on xen/arch/x86/setup.c
> +    if( sl_status )
`if (`  (Space before the bracket too)

2022-09-06 08:15 UTC, Stojek139808 commented on xen/arch/x86/setup.c
> +    if( sl_status )
My bad, fixed it.

2022-09-06 08:20 UTC, Stojek139808 commented on xen/arch/x86/boot/head.S
> +        movl $1, sym_esi(sl_status)
Yeah my bad, now it should be fine. As for stack, like I said in other comment, the rest of the stub is implemented in other PR, this will just get merged into it.

2022-09-07 11:30 UTC, miczyg1 commented on xen/arch/x86/setup.c
> +}
ALl of this should probably go to a separate file, like Intel_txt.c

2022-09-07 15:12 UTC, miczyg1 requested changes

2022-09-07 15:12 UTC, miczyg1 commented on xen/arch/x86/include/asm/intel_txt.h
> +void protect_txt_mem_regions(void);
```suggestion
void protect_txt_mem_regions(void);

```

2022-09-07 15:12 UTC, miczyg1 commented on xen/arch/x86/intel_txt.c
> +}
```suggestion
}

```

2022-09-07 15:12 UTC, miczyg1 commented on xen/arch/x86/tboot.c
> +    if ( !tboot_in_measured_env() && sl_status == 0 )
Do we still need this change?

2022-09-07 21:25 UTC, miczyg1 commented on xen/arch/x86/include/asm/intel_txt.h
> +void protect_txt_mem_regions(void);
Applied

2022-09-07 21:25 UTC, miczyg1 commented on xen/arch/x86/intel_txt.c
> +}
Applied

2022-09-07 21:25 UTC, miczyg1 commented on xen/arch/x86/tboot.c
> +    if ( !tboot_in_measured_env() && sl_status == 0 )
Removed as it is not needed.

2022-09-07 21:26 UTC, miczyg1 commented on xen/arch/x86/boot/head.S
> +        .long 0
Yes, that is something that we need to fix later.

2022-09-07 21:27 UTC, merged